# arxiv/registry

FROM centos:centos7

WORKDIR /opt/arxiv/

RUN yum install -y epel-release && yum install -y which mysql mysql-devel ca-certificates gcc python36 python36-devel wget && yum clean all
RUN wget https://bootstrap.pypa.io/get-pip.py && /usr/bin/python3.6 get-pip.py
RUN pip install -U pipenv uwsgi
ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8

ADD Pipfile Pipfile.lock /opt/arxiv/
ADD users/ /opt/arxiv/users/
RUN pipenv install /opt/arxiv/users/ --skip-lock

ENV PATH "/opt/arxiv:${PATH}"

ADD registry/wsgi.py registry/uwsgi.ini registry/create_client.py registry/create_db.py /opt/arxiv/
ADD registry/registry/ /opt/arxiv/registry/

ENV APPLICATION_ROOT "/"

EXPOSE 8000

ENTRYPOINT ["pipenv", "run"]
CMD ["uwsgi", "--ini", "/opt/arxiv/uwsgi.ini"]
