# arxiv/accounts


FROM python:3.11.8-bookworm

# Do not update+upgrade. The base image is kept up to date.  Also destroys
# ability to cache.

ARG git_commit

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    LC_ALL=en_US.utf8 \
    LANG=en_US.utf8

WORKDIR /arxiv-auth/accounts

RUN apt-get -y install default-libmysqlclient-dev

RUN pip install -U pip uv
COPY accounts/uv.lock accounts/pyproject.toml ./
COPY accounts/accounts ./

# Need arxiv-auth from same git repo
COPY arxiv-auth/arxiv_auth /arxiv-auth/arxiv_auth
COPY arxiv-auth/pyproject.toml arxiv-auth/poetry.lock /arxiv-auth/arxiv_auth

# RUN uv sync --frozen --no-dev

# ENV PATH="/app:${PATH}"

# ADD accounts/wsgi.py accounts/uwsgi.ini ./
# ADD accounts/accounts/ ./
# ADD fonts/montserrat.ttf ./fonts/montserrat.ttf

# ENV CAPTCHA_FONT="/arxiv-auth/accounts/fonts/montserrat.ttf"
# ENV APPLICATION_ROOT="/"

# EXPOSE 8000

# ENTRYPOINT ["uv", "run"]
# CMD ["uwsgi", "--ini", "/arxiv-auth/accounts/uwsgi.ini"]
