# arxiv/accounts-worker

FROM arxiv/base:latest

ADD requirements/prod.txt /opt/arxiv/requirements.txt
RUN pip install -U pip && pip install -r /opt/arxiv/requirements.txt

ENV PATH "/opt/arxiv:${PATH}"

ADD accounts/ /opt/arxiv/accounts/

WORKDIR /opt/arxiv/
ENTRYPOINT ["celery", "worker"]
CMD ["-A", "accounts.worker.celery_app", "--loglevel=INFO", "-E", "--concurrency=4"]
