# arxiv/registry

FROM arxiv/base:latest

WORKDIR /opt/arxiv/

RUN yum install -y which mysql mysql-devel
RUN pip install -U pip pipenv
ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8

ADD Pipfile Pipfile.lock /opt/arxiv/
RUN pipenv install

ADD users/ /opt/arxiv/users/
RUN pipenv install /opt/arxiv/users/ --skip-lock

ENV PATH "/opt/arxiv:${PATH}"

ADD registry/wsgi.py /opt/arxiv/
ADD registry/registry/ /opt/arxiv/registry/
ADD registry/create_client.py /opt/arxiv/
ADD registry/create_db.py /opt/arxiv/

EXPOSE 8000

ENTRYPOINT ["pipenv", "run"]
CMD ["uwsgi", "--http-socket", ":8000", \
     "-M", \
     "-t 3000", \
     "--manage-script-name", \
     "--processes", "1", \
     "--threads", "1", \
     "--queue", "0", \
     "--mount", "/=wsgi.py", \
     "--logformat", "%(addr) %(addr) - %(user_id)|%(session_id) [%(rtime)] [%(uagent)] \"%(method) %(uri) %(proto)\" %(status) %(size) %(micros) %(ttfb)"]
