# arxiv/accounts

FROM centos:centos7

WORKDIR /opt/arxiv/

RUN yum install -y epel-release && yum install -y mysql mysql-devel ca-certificates gcc python36 python36-devel wget && yum clean all
RUN wget https://bootstrap.pypa.io/get-pip.py && /usr/bin/python3.6 get-pip.py
RUN pip install -U pipenv uwsgi
ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8

ADD Pipfile Pipfile.lock /opt/arxiv/
ADD users/ /opt/arxiv/users/
RUN pipenv install /opt/arxiv/users/ --skip-lock

ENV PATH "/opt/arxiv:${PATH}"

ADD accounts/wsgi.py /opt/arxiv/
ADD accounts/accounts/ /opt/arxiv/accounts/
ADD fonts/montserrat.ttf /opt/arxiv/fonts/montserrat.ttf

ENV CAPTCHA_FONT "/opt/arxiv/fonts/montserrat.ttf"

EXPOSE 8000

ENTRYPOINT ["pipenv", "run", "uwsgi"]
CMD ["--http-socket", ":8000", \
     "-M", \
     "-t 3000", \
     "--manage-script-name", \
     "--processes", "8", \
     "--threads", "1", \
     "--async", "100", \
     "--ugreen", \
     "--mount", "/user=wsgi.py", \
     "--wsgi-disable-file-wrapper", \
     "--logformat", "%(addr) %(addr) - %(user_id)|%(session_id) [%(rtime)] [%(uagent)] \"%(method) %(uri) %(proto)\" %(status) %(size) %(micros) %(ttfb)"]
