name: Run Python Tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WITH_INTEGRATION: 1
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the dependenices
        run: uv sync --directory arxiv_auth --locked --all-extras --dev

      - name: Test with pytest
        run: |
          uv run --directory arxiv_auth pytest --cov=browse --cov-fail-under=80 tests

      - name: Ruff lint check
        run: |
          uv pip --directory arxiv_auth install ruff
          uv run --directory arxiv_auth ruff check --output-format=github browse
